#166789995 Enable Social Login via Google, Facebook and Twitter
andela/ah-92explorers-backend pull request #24
Opened 2019-07-02 05:48 UTC by niyoceles

#### What does this PR do?
- Enable login using Google, Facebook, and Twitter
#### Description of Task to be completed
- Configure passport to enable social login
- Create an application to Google, Facebook, and Twitter
#### How should this be manually tested?
1. Run the following commands in Terminal
```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-enable-social-login-166789995
```
2. run `npm install`
3. run `npm run start`

4. Using Google Chrome (or any other browser) 
- `http://localhost:3000/auth/facebook`
- `http://localhost:3000/auth/google`
- `http://localhost:3000/auth/twitter`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789995](https://www.pivotaltracker.com/story/show/166789995)
#### Screenshots (if appropriate)
N/A

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-03 07:22 UTC, elemanhillary-zz submitted a review, later dismissed
social login via social platforms work

2019-07-03 07:40 UTC, Hervera submitted a review, later dismissed

2019-07-03 07:44 UTC, IsaiahRn submitted a review, later dismissed
Social login enabled, it can be merged!

2019-07-03 07:59 UTC, kodek-sleuth requested changes
After success the travis file should run `npm run coveralls` we need that coverage

2019-07-03 09:25 UTC, Hervera commented on tests/passport.test.js
> +    http.get('http://localhost:3000/auth/facebookk', (res) => {
Change the route name to http://localhost:3000/auth/facebook

2019-07-03 12:35 UTC, elemanhillary-zz requested changes
Fix Missing trailing comma comma-dangle and the indentation space warnings from Hound please

2019-07-08 07:44 UTC, elemanhillary-zz requested changes
fix the comma dangle warning, and append a new line at EOF in `.travis.yml`

2019-07-09 07:31 UTC, Hervera submitted a review, later dismissed

2019-07-09 07:46 UTC, elemanhillary-zz requested changes
fix the `.travis.yml` file as @kodek-sleuth stated with sample screenshots on how it should be

2019-07-10 15:07 UTC, IsaiahRn submitted a review, later dismissed

2019-07-10 16:01 UTC, Hervera submitted a review, later dismissed

2019-07-10 16:16 UTC, niyoceles commented
> .travis.yml

I fixed that.

2019-07-10 19:43 UTC, kodek-sleuth submitted a review, later dismissed
This PR is ready to be merged

2019-07-10 21:39 UTC, kodek-sleuth submitted a review, later dismissed
This PR is ready to be merged

2019-07-11 05:27 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-11 05:36 UTC, elemanhillary-zz submitted a review, later dismissed
approved

2019-07-15 07:32 UTC, kodek-sleuth submitted a review, later dismissed
This PR is ready to be merged

2019-07-15 07:57 UTC, Hervera submitted a review, later dismissed
Ready to be marged

2019-07-15 09:18 UTC, kodek-sleuth approved these changes
This PR is ready to be merged

2019-07-15 11:19 UTC, elemanhillary-zz approved these changes
ready for merging

2019-07-15 11:20 UTC, Hervera approved these changes
Ready to be marged

2019-07-16 07:01 UTC, IsaiahRn approved these changes
ready to be merged!

2019-07-16 07:25 UTC, merged