#166925789 User Authentication Pages
andela/ah-92explorers-backend pull request #28
Opened 2019-07-02 18:47 UTC by elemanhillary

#### What does this PR do?
- Add user authentication UI pages

#### Description of Task to be completed
- Enable user to interact with backend

#### How should this be manually tested?
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout gh-pages
```
- open internet browser
- run `index.html`

#### Any background context you want to provide?
- None

#### What are the relevant pivotal tracker stories?
[166925789](https://www.pivotaltracker.com/story/show/166925789)
#### Screenshots (if appropriate)
![Imgur](https://i.imgur.com/t0h0RoI.png)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-02 21:27 UTC, IsaiahRn approved these changes
I loved the way you just kept it simple

2019-07-03 05:08 UTC, Hervera approved these changes

2019-07-03 06:37 UTC, niyoceles approved these changes

2019-07-03 07:48 UTC, kodek-sleuth requested changes
Edit PR and add that one needs to run those commands in terminal

2019-07-08 08:23 UTC, kodek-sleuth approved these changes

2019-07-08 10:04 UTC, merged