#166789994 Users Should Be Able to Reset Password via Email
andela/ah-92explorers-backend pull request #32
Opened 2019-07-05 11:46 UTC by Hervera

#### What does this PR do?
It lets a user to reset the password via email

#### Description of Task to be completed
- Add nodemailer
- write send mail functionalities
- write reset password functionalities
- Add tests

#### How should this be manually tested?
1. Run the following commands in Terminal
```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-user-sign-out-166789992
run `npm install`
Install your local database in Postgres
Rename `.env.sample` to `.env` Open it and replace  `database-name` your created database
run `npm run start`
```
2. Send the reset password link using email
- use `POST` method with your registered email in the body in this route `http://localhost:3000/api/v1/password`

3. Visit your email to get the reset password link which has a token

4. Reset Password
- use `PUT` method with the token received and add new password in the body using this route `http://localhost:3000/api/v1/password` 

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166789994](https://www.pivotaltracker.com/story/show/166789994)

#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-09 11:38 UTC, Hervera commented on helpers/sendEmail.js
> +const sendEmail = (userEmail, token, template) => new Promise(async (resolve, reject) => {
Use `async/await` instead of `new Promise()`

2019-07-10 06:11 UTC, kodek-sleuth requested changes
Please rebase from develop before further reviewing

2019-07-10 12:11 UTC, kodek-sleuth requested changes

2019-07-10 12:11 UTC, kodek-sleuth commented on controllers/resetPasswordController.js
> +const User = models.users;
Please de-structure this line and please use a small cased User object

2019-07-10 12:32 UTC, elemanhillary-zz reviewed
fix the issues reflected in the `review comments`

2019-07-10 12:32 UTC, elemanhillary commented on index.js
> +app.get('/reset-password/:token', (req, res) => {
line `29` of `index.js` should be put in `routers` folder, kindly follow the project structure to fix that.

2019-07-10 12:37 UTC, elemanhillary-zz requested changes

2019-07-10 12:37 UTC, elemanhillary commented on index.js
> +app.get('/reset-password/:token', (req, res) => {
line `29` of `index.js` should be in `routes` folder, kindly check the project structure to fix it

2019-07-10 12:38 UTC, elemanhillary-zz requested changes
fix merge conflicts

2019-07-10 13:35 UTC, Hervera commented
> fix merge conflicts

2019-07-10 14:13 UTC, niyoceles submitted a review, later dismissed

2019-07-10 15:03 UTC, IsaiahRn submitted a review, later dismissed
It is ready to be merged

2019-07-10 15:58 UTC, elemanhillary-zz submitted a review, later dismissed

2019-07-10 16:01 UTC, kodek-sleuth submitted a review, later dismissed
This PR is ready too be merged

2019-07-10 16:02 UTC, Krasivaya approved these changes

2019-07-10 16:04 UTC, Krasivaya approved these changes

2019-07-10 16:04 UTC, Krasivaya submitted a review, later dismissed
Ready to be merged

2019-07-10 16:12 UTC, niyoceles submitted a review, later dismissed

2019-07-11 05:41 UTC, elemanhillary-zz reviewed
ready for merge

2019-07-11 05:42 UTC, elemanhillary-zz requested changes
ready for merge

2019-07-11 05:42 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-11 07:19 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-11 12:29 UTC, niyoceles submitted a review, later dismissed

2019-07-13 11:26 UTC, kodek-sleuth commented on .env.example
> +SENDER_EMAIL=
Please complete these lines

2019-07-13 11:29 UTC, kodek-sleuth requested changes

2019-07-13 11:29 UTC, kodek-sleuth commented on controllers/resetPasswordController.js
> +      return res.status(500).json({ error });
its not advisable to return an error object in that way, its better to specify the error you want returned

2019-07-14 18:57 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-15 08:02 UTC, niyoceles submitted a review, later dismissed

2019-07-15 08:32 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-16 08:20 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-16 08:20 UTC, kodek-sleuth approved these changes

2019-07-16 08:21 UTC, IsaiahRn approved these changes
it can be approved

2019-07-16 08:23 UTC, merged