#166789990 User Should  Receive A Verification Email Upon Successful Signup
andela/ah-92explorers-backend pull request #34
Opened 2019-07-07 00:15 UTC by IsaiahRn

#### What does this PR do?

- Verify user account

#### Description of Task to be completed

- User should be able to receive a verification link via email upon successful signup.

#### How should this be manually tested?

1. Run the following commands in Terminal

```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-verification-email-166789990
run `npm install`
Add environment variables as indicated in `.env.sample` 
run `npm start`
```

2.  Register a user via `http://localhost:3000/api/v1/signup`, 

3. A verification email will be sent to you after successfully signing up.

4. Go to your email and verify user account via a link sent in the email.

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[166789990](https://www.pivotaltracker.com/story/show/166789990)
#### Screenshots (if appropriate)

- After registration, you will an email as shown below:

<img width="830" alt="Screen Shot 2019-07-06 at 21 52 13" src="https://user-images.githubusercontent.com/40357462/60762295-c12e8e80-a05c-11e9-88ad-54a387397d75.png">

- Then, you will be verified.

<img width="1320" alt="Screen Shot 2019-07-06 at 21 52 46" src="https://user-images.githubusercontent.com/40357462/60762296-c1c72500-a05c-11e9-9358-9791a52d8d91.png">

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-08 07:51 UTC, elemanhillary-zz requested changes
kindly follow the endpoints in the `readme.md` file, it should be `/api/` not `/api/v1`

2019-07-10 11:57 UTC, kodek-sleuth approved these changes

2019-07-10 11:57 UTC, kodek-sleuth commented on controllers/auth.js
> +    const newUser = await db.users.create({
destructure all your objects where possible

2019-07-10 11:58 UTC, niyoceles submitted a review, later dismissed

2019-07-10 12:04 UTC, kodek-sleuth requested changes
Please use object restructuring where ever possible

2019-07-10 12:21 UTC, elemanhillary commented
> Please use object restructuring where ever possible

2019-07-10 12:31 UTC, Hervera submitted a review, later dismissed

2019-07-10 14:11 UTC, elemanhillary-zz requested changes
squash your commit messages since they have exceeded the required number of messages a PR should have

2019-07-10 15:04 UTC, Hervera approved these changes

2019-07-10 15:57 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-10 16:09 UTC, kodek-sleuth approved these changes
This pr is ready to be merged

2019-07-10 16:34 UTC, niyoceles approved these changes

2019-07-10 16:47 UTC, merged