#166790002 users should be able to comment on articles
andela/ah-92explorers-backend pull request #41
Opened 2019-07-14 18:04 UTC by elemanhillary

#### What does this PR do?
- Adds a feature to comment on an article.

#### Description of Task to be completed
- Enable user comment(s) on articles, both authored by the user and those not authored by the user

#### How should this be manually tested?
 ```shell
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-comment-on-article-166790002
npm install
npm start
```
- Navigate to `localhost:3000/api/articles/:slug/comments`

#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
[166790002](https://www.pivotaltracker.com/story/show/166790002)

#### Screenshots (if appropriate)
![Imgur](https://i.imgur.com/hVTIMPU.png)

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-14 20:53 UTC, IsaiahRn submitted a review, later dismissed
Kindly, make these changes:

1. Change the footer of your commit message, We don't use Maintains on features `[Maintains ##166790002]`, it should be Starts, Finishes or Delivers and keep only one `#`

2. Capitalize every first letter on the PR title

2019-07-15 07:38 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-15 07:38 UTC, kodek-sleuth commented on controllers/article.js
> +    res.status(400).json({ message: 'article creation failed' });
please use an error key to send an error message

2019-07-17 12:15 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-17 12:17 UTC, IsaiahRn submitted a review, later dismissed
This PR is ready to be merged!

2019-07-17 12:19 UTC, Hervera submitted a review, later dismissed
Ready to be marged

2019-07-17 12:21 UTC, niyoceles submitted a review, later dismissed

2019-07-20 09:02 UTC, niyoceles submitted a review, later dismissed
ready to merge

2019-07-22 08:10 UTC, IsaiahRn submitted a review, later dismissed

2019-07-22 08:16 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-22 08:49 UTC, dmithamo requested changes

2019-07-22 08:49 UTC, dmithamo commented on controllers/comment.js
> +      return;
Remove unnecessary `return`

2019-07-22 08:49 UTC, dmithamo commented on controllers/comment.js
> +            createdAt,
Add a reference to the article. i.e,
```
article: {
   slug: `article-slug-2`
}
```

2019-07-22 09:02 UTC, dmithamo approved these changes

2019-07-22 09:02 UTC, niyoceles approved these changes

2019-07-22 09:06 UTC, niyoceles approved these changes

2019-07-22 09:22 UTC, kodek-sleuth approved these changes

2019-07-22 09:27 UTC, merged