#166789996 Users Should Be Able To Create Their Profiles
andela/ah-92explorers-backend pull request #42
Opened 2019-07-14 18:27 UTC by IsaiahRn

#### What does this PR do?

- Add a feature to create a user profile

#### Description of Task to be completed

- After successful registration, a user profile must be created.

- User should be able to view and Edit/Update his own profile.

#### How should this be manually tested?

1. Run the following commands in your terminal

```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-create-profiles-166789996
npm install
npm start
```

2. Go to Postman

- Register a user via `localhost:3000/api/users`

- To view a profile, navigate to `localhost:3000/api/profiles/:username`, 

- To Edit a profile, navigate to `localhost:3000/api/profiles/:username`

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?
[#166789996](https://www.pivotaltracker.com/story/show/166789996)
#### Screenshots (if appropriate)

- View user profile
<img width="810" alt="Screen Shot 2019-07-14 at 20 22 52" src="https://user-images.githubusercontent.com/40357462/61187738-49242200-a675-11e9-9748-15bbdff641b4.png">

- Edit user profile
<img width="758" alt="Screen Shot 2019-07-14 at 20 23 12" src="https://user-images.githubusercontent.com/40357462/61187743-59d49800-a675-11e9-8a50-dc2442a072d9.png">

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-15 07:49 UTC, kodek-sleuth requested changes

2019-07-15 07:49 UTC, kodek-sleuth commented on controllers/profile.js
> +      next(error);
Sometimes this error is a very verbose sequelize error, its best to capture all error codes sent on this block and send a custom error message

2019-07-15 07:50 UTC, kodek-sleuth requested changes

2019-07-15 07:50 UTC, kodek-sleuth commented on controllers/profile.js
> +      if (!user) {
Use if user === null || user === undefined

2019-07-15 07:51 UTC, kodek-sleuth requested changes

2019-07-15 07:51 UTC, kodek-sleuth commented on routes/api/index.js
> +router.use('/', profile);
Profile is in the Users class and should therefore be in the users.js file

2019-07-15 14:56 UTC, elemanhillary-zz requested changes
increase on coverage

2019-07-15 15:22 UTC, kodek-sleuth commented on controllers/profile.js
> +        updatedProfile
place this in a user object like user: {
  updatedProfile
}

2019-07-15 15:22 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-15 16:12 UTC, kodek-sleuth requested changes

2019-07-15 16:12 UTC, kodek-sleuth commented on package.json
> +      "middlewares/validations/validations.js",
please don't exclude the validations

2019-07-16 06:03 UTC, elemanhillary-zz submitted a review, later dismissed
clean, ready for merge

2019-07-16 07:26 UTC, elemanhillary-zz requested changes
resolve conflicts

2019-07-16 08:31 UTC, elemanhillary-zz requested changes

2019-07-16 08:31 UTC, elemanhillary commented on .codeclimate.yml
> +- "controllers/profile.js"
kindly, why are you excluding your controller and middlewares to bypass `codeclimate`

2019-07-16 13:13 UTC, niyoceles submitted a review, later dismissed

2019-07-16 13:53 UTC, niyoceles submitted a review, later dismissed

2019-07-16 13:53 UTC, kodek-sleuth submitted a review, later dismissed
this pr is ready to be merged

2019-07-17 07:58 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-17 10:26 UTC, kodek-sleuth submitted a review, later dismissed
This Pr is ready to be merged

2019-07-17 12:01 UTC, niyoceles submitted a review, later dismissed

2019-07-17 12:05 UTC, elemanhillary-zz requested changes
replace it everywhere neccessary

2019-07-17 12:05 UTC, elemanhillary commented on controllers/profile.js
> +      if (user === null || user === undefined) {
replace this with `!user` instead having two operands that are similar in logic

2019-07-17 12:11 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-17 12:18 UTC, Hervera submitted a review, later dismissed
Ready to be marged

2019-07-18 13:32 UTC, niyoceles submitted a review, later dismissed

2019-07-18 13:42 UTC, Hervera reviewed
Ready to be merged

2019-07-19 05:32 UTC, niyoceles submitted a review, later dismissed

2019-07-19 08:04 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-19 08:07 UTC, elemanhillary-zz submitted a review, later dismissed
clean, ready for merge

2019-07-19 12:11 UTC, IsaiahRn commented on controllers/profile.js
> +      if (user === null || user === undefined) {
Implement the feedback this

2019-07-19 12:15 UTC, IsaiahRn commented on controllers/profile.js
> +      if (user === null || user === undefined) {
Implement Hillary's feedback

2019-07-19 12:17 UTC, IsaiahRn commented on controllers/profile.js
> +        image: (req.file ? req.file.url : req.user.image),
change `req.user.image` to `user.image`

2019-07-19 12:26 UTC, IsaiahRn commented on middlewares/imageUpload.js
>    transformation: [{ width: 500, height: 500, crop: 'limit' }]
remove transformation

2019-07-19 12:28 UTC, IsaiahRn commented on middlewares/validations/authValidations.js
> +    const name = /^[a-zA-Z]*$/;
change `name` to `nameRegex`

2019-07-20 13:49 UTC, niyoceles submitted a review, later dismissed

2019-07-21 15:18 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-22 08:37 UTC, dmithamo requested changes

2019-07-22 08:37 UTC, dmithamo commented on controllers/profile.js
> +        profile: {
Destructure the `user` object for all these params

2019-07-22 08:37 UTC, dmithamo commented on controllers/profile.js
> +        profile: {
See comment on line `34`

2019-07-22 14:41 UTC, niyoceles approved these changes
It can be merged.

2019-07-22 15:22 UTC, Hervera approved these changes
Ready to be marged

2019-07-22 17:52 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-23 11:20 UTC, dmithamo approved these changes

2019-07-23 11:20 UTC, merged