#166789999 Users should be able to give a Rating to an Article
andela/ah-92explorers-backend pull request #45
Opened 2019-07-15 20:26 UTC by niyoceles

#### What does this PR do?
- user able to rate an article
#### Description of Task to be completed
- Create a relationship database
- Write a test
- Write a documentation
#### How should this be manually tested?
1. Run the following commands in Terminal
```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-user-rating-article-166789999
```
2. npm install -g sequelize-cli

3. run `npm install`

4. Install your local database in Postgres

4. Rename `.env.sample` to `.env` Open it and replace  `database-name` your created database

5. run in terminal `sequelize db:migrate

6. run `npm run start`

7. Using Postman
- `POST` `localhost:3000/api/articles/<slug>/rate`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789999](https://www.pivotaltracker.com/story/show/166789999)
#### Screenshots (if appropriate)
<img width="1018" alt="Screen Shot 2019-07-15 at 22 22 05" src="https://user-images.githubusercontent.com/30776949/61246441-1f3f2e00-a74f-11e9-99e5-ad6ebc0deaf3.png">
<img width="1030" alt="Screen Shot 2019-07-15 at 22 23 54" src="https://user-images.githubusercontent.com/30776949/61246517-4b5aaf00-a74f-11e9-9674-fc8f30e1d94c.png">
<img width="1024" alt="Screen Shot 2019-07-15 at 22 25 26" src="https://user-images.githubusercontent.com/30776949/61246592-7e04a780-a74f-11e9-8c2e-617525470cb0.png">

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-19 06:19 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-19 07:38 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-19 08:07 UTC, IsaiahRn submitted a review, later dismissed

2019-07-19 13:06 UTC, niyoceles commented on controllers/rating.js
> +      const findArticle = await articles.findOne({
rename findArticle to `article`

2019-07-19 13:07 UTC, niyoceles commented on controllers/rating.js
> +      const findAuthor = await users.findOne({
rename findAuthor  to `author`

2019-07-19 13:10 UTC, niyoceles commented on controllers/rating.js
> +      const findRate = await rating.findOne({
Remove checking existing rating

2019-07-19 13:14 UTC, niyoceles commented on controllers/rating.js
> +      return res.status(200).json({
remove returning existing rate

2019-07-20 13:50 UTC, IsaiahRn submitted a review, later dismissed
It can be merged

2019-07-21 15:15 UTC, Hervera approved these changes
Ready to be merged

2019-07-22 06:20 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-22 09:04 UTC, Hervera requested changes
Rework on making average of ratings

2019-07-22 14:59 UTC, Hervera submitted a review, later dismissed
Ready to be approved

2019-07-22 15:05 UTC, IsaiahRn submitted a review, later dismissed

2019-07-22 17:55 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 11:57 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-23 11:58 UTC, IsaiahRn approved these changes

2019-07-23 11:59 UTC, Hervera approved these changes
Ready to be approved

2019-07-23 12:01 UTC, merged