#166790009 Add Search Functionality And Custom filtering Based on Parameters
andela/ah-92explorers-backend pull request #46
Opened 2019-07-17 10:10 UTC by elemanhillary

#### What does this PR do?
- Adds search functionality and custom filtering based on parameters

#### Description of Task to be completed
- Enable user to filter articles by author, tag, title and keywords
- Enable a user to get an article that matches only the criteria that matches the criteria for the article they want.

#### How should this be manually tested?
```bash
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-search-functionality-166790009
npm install
npm start
```
Navigate to `localhost:3000/api/articles/:tag?/:author?/:title?/:keyword?`

#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
[166790009](https://www.pivotaltracker.com/story/show/166790009)
#### Screenshots (if appropriate)

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-18 21:24 UTC, niyoceles requested changes
Squash all commits to a single commit.

2019-07-19 08:12 UTC, niyoceles submitted a review, later dismissed

2019-07-19 08:48 UTC, Hervera submitted a review, later dismissed
Ready to be marged

2019-07-19 08:54 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-19 10:56 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-19 10:58 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-19 10:58 UTC, IsaiahRn submitted a review, later dismissed

2019-07-19 12:43 UTC, elemanhillary commented on controllers/search.js
> +      return res.status(204).json({ error: 'no results' });
change `204` to `404`

2019-07-19 12:53 UTC, elemanhillary commented on tests/search.test.js
> +  it('should return 204 on empty search results', (done) => {
change string `204` to `404`

2019-07-20 09:04 UTC, niyoceles submitted a review, later dismissed

2019-07-22 08:12 UTC, IsaiahRn approved these changes

2019-07-22 08:14 UTC, IsaiahRn requested changes
Kindly. squash your commits

2019-07-22 08:17 UTC, elemanhillary commented
> Kindly. squash your commits

had forgotten that hehehehe

2019-07-22 18:02 UTC, IsaiahRn approved these changes
It can be merged

2019-07-22 18:07 UTC, niyoceles approved these changes

2019-07-23 05:21 UTC, Hervera requested changes
In files changed, I don't see the code of your controller

2019-07-23 12:09 UTC, niyoceles approved these changes

2019-07-25 08:56 UTC, niyoceles approved these changes

2019-07-25 08:57 UTC, IsaiahRn approved these changes

2019-07-25 08:57 UTC, Hervera approved these changes
Ready to be merged

2019-07-25 08:58 UTC, merged