#166790000- Users Should Be Able To Fetch Article's Ratings
andela/ah-92explorers-backend pull request #47
Opened 2019-07-17 10:16 UTC by kodek-sleuth

#### What does this PR do?
Enable a user to fetch ratings of an article
#### Description of Task to be completed
Set up a method to fetch ratings of an article
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-fetch-article-rating-166790000
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgres://username:password@localhost:5432/authorshaven
DATABASE_=postgres://username:password@localhost:5432/testing-ah
SECRET=whatever you want it to be
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Install and setup Postman to consume CRUD endpoints
6. Run the following requests in Postman using `localhost:3000`
## Endpoints
|  Method  |  Endpoint  |  Task  |
|  --- |  --- |  ---  |
|  `GET`  |  `/api/article/:articleSlug/ratings`  |  `fetches all article ratings`  |
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166790017](https://www.pivotaltracker.com/story/show/166790017)
#### Screenshots (if appropriate)
N/A
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-18 18:00 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-18 18:01 UTC, niyoceles submitted a review, later dismissed

2019-07-18 18:04 UTC, IsaiahRn submitted a review, later dismissed
it can be merged!

2019-07-18 20:43 UTC, Hervera requested changes
Remove conflicts & use Sequelize instead of SQL queries

2019-07-19 06:16 UTC, niyoceles approved these changes

2019-07-19 08:11 UTC, IsaiahRn submitted a review, later dismissed
ready to be merged

2019-07-19 08:17 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-19 08:52 UTC, Hervera commented on migrations/20190704173059-createTableUsers.js
> +
Add the second blank line

2019-07-19 08:54 UTC, Hervera commented on routes/api/ratings.js
> +router.get('/article/:articleSlug/rating', ratingController.getRating);
Make `rating` in plural, to be `ratings` as you are fetching article's ratings

2019-07-22 15:40 UTC, niyoceles requested changes
rename `ratings.js` in the controller folder to  `rating.js` all the files in a controller folder must be in single

2019-07-23 05:23 UTC, Hervera requested changes
Remove the conflicts

2019-07-23 07:55 UTC, elemanhillary-zz requested changes

2019-07-23 07:55 UTC, elemanhillary commented on controllers/ratings.js
> +      switch (true) {
no `default` case for the switch statement.

2019-07-23 07:55 UTC, elemanhillary commented on controllers/ratings.js
> +        case findRate === null:
in which cases are you using the `switch` statement
```javascript
if (!findRate) {
  await ratings.create({
    rating,
    articleSlug: slug,
    userId: user.id
  });
  return res.status(201).json({
    message: 'you have successfully rated this article',
    rating: {
      rating,
      author: author.username,
      title,
      body
    }
  });
}
return res.status(200).json({
  message: 'you already rated this article',
  rating
});
```
may my request be put under your consideration. But kindly compare and check before you change

2019-07-23 07:55 UTC, elemanhillary commented on middlewares/checkArticleOwner.js
> +import models from '../models/index';
this file was renamed to `checkResourceOwner`

2019-07-23 07:55 UTC, elemanhillary-zz requested changes
resolve the merge conflicts

2019-07-23 11:11 UTC, IsaiahRn submitted a review, later dismissed
It can be merged!

2019-07-23 11:14 UTC, niyoceles submitted a review, later dismissed

2019-07-23 11:14 UTC, Hervera submitted a review, later dismissed

2019-07-23 12:03 UTC, IsaiahRn approved these changes
It can be merged!

2019-07-23 12:03 UTC, IsaiahRn requested changes
solve merge conflicts

2019-07-23 14:44 UTC, IsaiahRn submitted a review, later dismissed

2019-07-23 14:57 UTC, niyoceles submitted a review, later dismissed

2019-07-23 15:06 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-24 08:49 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-24 08:50 UTC, niyoceles approved these changes

2019-07-24 08:57 UTC, Hervera approved these changes
Ready to be merged

2019-07-24 08:58 UTC, merged