#166790019 - Comments Should Be Able To Track Edit History
andela/ah-92explorers-backend pull request #51
Opened 2019-07-19 10:02 UTC by kodek-sleuth

#### What does this PR do?
Should track comment edit history
#### Description of Task to be completed
Setup model and controller to persist data and validation
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-fetch-article-rating-166790003
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgres://username:password@localhost:5432/authorshaven
DATABASE_=postgres://username:password@localhost:5432/testing-ah
SECRET=whatever you want it to be
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Install and setup Postman to consume CRUD endpoints
6. Run the following requests in Postman using `localhost:3000`
## Endpoints
|  Method  |  Endpoint  |  Task  |
|  --- |  --- |  ---  |
|  `PATCH`  |  `/api/:commentId/history`  |  `track history`  |
|  `GET`  |  `/api/:commentId/history`  |  `get comment history`  |
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166790019](https://www.pivotaltracker.com/story/show/166790019)
#### Screenshots (if appropriate)
N/A
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-24 07:58 UTC, niyoceles submitted a review, later dismissed

2019-07-24 08:02 UTC, elemanhillary-zz requested changes

2019-07-24 08:02 UTC, elemanhillary commented on helpers/sqlRawQueries.js
> +const getArticleAndRatings = articleSlug => `select articles.title, articles.body, articles.image, ratings.rating,
we talked about these queries. kindly eliminate them

2019-07-24 10:13 UTC, elemanhillary-zz requested changes
resolve merge conflicts

2019-07-24 11:18 UTC, IsaiahRn submitted a review, later dismissed

2019-07-24 11:19 UTC, niyoceles submitted a review, later dismissed

2019-07-24 11:22 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-25 07:44 UTC, elemanhillary-zz requested changes
resolve merge conflicts

2019-07-25 10:10 UTC, niyoceles submitted a review, later dismissed

2019-07-25 10:12 UTC, niyoceles submitted a review, later dismissed

2019-07-25 10:12 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-25 10:13 UTC, IsaiahRn submitted a review, later dismissed

2019-07-31 10:58 UTC, niyoceles approved these changes
ready to be merged

2019-07-31 11:01 UTC, elemanhillary-zz requested changes
coverage decreased kindly fix it

2019-07-31 11:40 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-31 11:50 UTC, niyoceles submitted a review, later dismissed

2019-07-31 11:50 UTC, IsaiahRn submitted a review, later dismissed

2019-07-31 12:36 UTC, IsaiahRn approved these changes

2019-07-31 12:36 UTC, niyoceles submitted a review, later dismissed

2019-07-31 12:45 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-31 12:55 UTC, IsaiahRn submitted a review, later dismissed

2019-08-14 14:34 UTC, Hervera submitted a review, later dismissed

2019-08-15 13:47 UTC, niyoceles requested changes

2019-08-15 13:47 UTC, niyoceles commented on tests/report.test.js
> -  it('Should not allow any user to  get report with data', (done) => {
Kindly don't remove this test

2019-08-16 09:32 UTC, niyoceles approved these changes

2019-08-16 09:32 UTC, elemanhillary-zz approved these changes
nice work, ready for merge

2019-08-16 09:33 UTC, Hervera approved these changes

2019-08-16 09:33 UTC, IsaiahRn approved these changes

2019-08-16 09:36 UTC, merged