#166790004 Users Should Follow Each Other
andela/ah-92explorers-backend pull request #52
Opened 2019-07-19 10:07 UTC by IsaiahRn

### What does this PR do?

- Users should be able to follow each other

#### Description of Task to be completed

- create follow endpoints

- verify the endpoint to allow only valid users

- write the following functionality

- make sure users cannot follow themselves

- make sure a user cannot follow a user multiple times

- add tests for the endpoints

- document feature using swagger

#### How should this be manually tested?

1. Run the following commands in the terminal.
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-Users-follow-unfollow-166790004
npm install
npm start
```

2. Test endpoints, via Postman:

- Follow a user `http://localhost:3000/api/:username/follow`

- Unfollow a user `http://localhost:3000/api/:username/unfollow`

- Fetch the user's followers `http://localhost:3000/api/followers`

- Fetch the user's following `http://localhost:3000/api/following`

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?
[#166790004](https://www.pivotaltracker.com/story/show/166790004)
#### Screenshots (if appropriate)

- Follow a user:
<img width="838" alt="Screen Shot 2019-07-19 at 11 54 10" src="https://user-images.githubusercontent.com/40357462/61527204-30708f00-aa1c-11e9-979d-8204e59b8362.png">

- Unfollow a user
<img width="846" alt="Screen Shot 2019-07-19 at 11 54 29" src="https://user-images.githubusercontent.com/40357462/61527234-3e261480-aa1c-11e9-83a3-b67b81681fca.png">

- Fetch followers
<img width="844" alt="Screen Shot 2019-07-19 at 11 59 06" src="https://user-images.githubusercontent.com/40357462/61527414-ad9c0400-aa1c-11e9-9580-f1d7a95d906b.png">

- Fetch following
<img width="845" alt="Screen Shot 2019-07-19 at 11 55 21" src="https://user-images.githubusercontent.com/40357462/61527266-50a04e00-aa1c-11e9-8819-2d9e165dbbac.png">

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-23 07:30 UTC, niyoceles submitted a review, later dismissed

2019-07-23 07:46 UTC, kodek-sleuth requested changes

2019-07-23 07:46 UTC, kodek-sleuth commented on controllers/followers.js
> +      : res.status(404).json({ errors: "You don't have followers" });
Please use `error` not `errors`

2019-07-23 07:48 UTC, kodek-sleuth requested changes

2019-07-23 07:48 UTC, kodek-sleuth commented on tests/followers.test.js
> +describe('Following a user', () => {
Please use seeders to further simplify your tests

2019-07-23 15:17 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 15:18 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-23 15:19 UTC, niyoceles submitted a review, later dismissed

2019-07-24 11:14 UTC, niyoceles submitted a review, later dismissed

2019-07-24 11:16 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-24 11:17 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-24 13:13 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-24 13:13 UTC, niyoceles submitted a review, later dismissed

2019-07-24 13:16 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-07-25 10:41 UTC, kodek-sleuth approved these changes

2019-07-25 10:46 UTC, niyoceles approved these changes

2019-07-25 11:49 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-25 12:15 UTC, merged