#166790007 Pagination Support for Articles
andela/ah-92explorers-backend pull request #54
Opened 2019-07-19 11:42 UTC by Hervera

#### What does this PR do?
It provides pagination support for article's

#### Description of Task to be completed
- add pagination of 10 ratings per page
- add page and/or limit as query params
- add metadata on every article's ratings page

#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-pagination-for-articles-166790007
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgresql://dbusername:dbpassword@localhost:5432/dbname
DATABASE_TEST=postgresql://dbusername:dbpassword@localhost:5432/dbnamefortest
SECRET=whatever you want it to be
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Install and setup Postman to consume CRUD endpoints
6. Run the following requests in Postman using `localhost:3000`
## Endpoints
|  Method  |  Endpoint  |  Task  |
|  --- |  --- |  ---  |
|  `GET`  |  `/api/articles/feed?page=1&limit=1`  |  `pagination support for articles`  |

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166790007](https://www.pivotaltracker.com/story/show/166790007)

#### Screenshots (if appropriate)
<img width="1098" alt="Screen Shot 2019-07-19 at 13 39 51" src="https://user-images.githubusercontent.com/25223709/61532640-b85d9580-aa2a-11e9-9c91-8b099d3e8962.png">

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-20 10:09 UTC, niyoceles requested changes
try to remove the files which are related to rating an article, some of those files have been changed in this `ft-user-rating-article-166789999` branch

2019-07-20 10:09 UTC, niyoceles commented on controllers/ratings.js
> +import models from '../models';
Remove this file `ratings.js` in controllers will no longer be used.

2019-07-23 11:19 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 15:14 UTC, niyoceles approved these changes

2019-07-23 15:15 UTC, kodek-sleuth approved these changes

2019-07-23 15:15 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-24 08:35 UTC, merged