#166790008 List Users Functionality
andela/ah-92explorers-backend pull request #55
Opened 2019-07-20 06:53 UTC by Hervera

#### What does this PR do?
Lists users functionality

#### Description of Task to be completed
  - add a route
  - add functionality of listing users
  - add tests
  - add a documentation

#### How should this be manually tested?

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166790008](https://www.pivotaltracker.com/story/show/166790008)

#### Screenshots (if appropriate)
<img width="1081" alt="Screen Shot 2019-07-20 at 08 53 18" src="https://user-images.githubusercontent.com/25223709/61575423-daf3bb00-aacb-11e9-963b-4e81cde24f57.png">

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-20 10:20 UTC, niyoceles requested changes

2019-07-20 10:20 UTC, niyoceles commented on controllers/ratings.js
> +import models from '../models';
Remove this file ratings.js in controllers will no longer be used.

2019-07-20 10:20 UTC, niyoceles commented on models/users.js
> -    provider: { type: DataTypes.STRING },
Please add this  column on users table `provider: { type: DataTypes.STRING },`

2019-07-23 11:16 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-23 11:17 UTC, elemanhillary-zz submitted a review, later dismissed
resolve merge conflicts

2019-07-23 16:25 UTC, niyoceles submitted a review, later dismissed

2019-07-23 16:25 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 16:27 UTC, IsaiahRn submitted a review, later dismissed
ready to be merged

2019-07-24 08:56 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-24 09:04 UTC, IsaiahRn approved these changes

2019-07-24 09:05 UTC, niyoceles submitted a review, later dismissed

2019-07-24 09:05 UTC, IsaiahRn requested changes
fix merge conflicts

2019-07-24 10:21 UTC, niyoceles approved these changes

2019-07-24 10:21 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-24 10:28 UTC, IsaiahRn approved these changes

2019-07-24 11:57 UTC, merged