#166790014 Users Should Be Able to Like a Specific Comment
andela/ah-92explorers-backend pull request #56
Opened 2019-07-20 13:05 UTC by niyoceles

#### What does this PR do?
Enables a user to like a comment
#### Description of Task to be completed
- To set up like a comment functionality
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-user-like-specific-comment-166790014
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgres://username:password@localhost:5432/authorshaven
DATABASE_=postgres://username:password@localhost:5432/authorshaven_test
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Run the following requests in Postman using `localhost:3000`
|  `POST`  |  `/api/article/comment/:articleId/like`  |  `like a comment`  |
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166790014](https://www.pivotaltracker.com/story/show/166790014)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-07-23 06:17 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 07:36 UTC, kodek-sleuth requested changes

2019-07-23 07:36 UTC, kodek-sleuth commented on tests/likeComment.test.js
> +  it('should login an user', (done) => {
You only need one test block of logging in a user

2019-07-23 11:14 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 15:32 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 15:41 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-23 15:44 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-23 15:44 UTC, IsaiahRn submitted a review, later dismissed

2019-07-24 13:17 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-24 13:18 UTC, IsaiahRn approved these changes

2019-07-25 08:40 UTC, dmithamo approved these changes

2019-07-25 08:41 UTC, merged