#166790012 Users Should Bookmark Articles For Reading Later
andela/ah-92explorers-backend pull request #61
Opened 2019-07-25 11:10 UTC by IsaiahRn

#### What does this PR do?

- Users should be able to bookmark articles for reading later

#### Description of Task to be completed

- Add bookmarking functionality

- Add tests for the endpoint

- Add documentation using swagger

#### How should this be manually tested?

1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-bookmark-articles-166790012
npm install
npm start
```

2. Test endpoints, via Postman:

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?
[#166790012](https://www.pivotaltracker.com/story/show/166790012)
#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-07-28 05:49 UTC, elemanhillary-zz requested changes
provide screen shot

2019-07-28 10:46 UTC, IsaiahRn commented
> provide screen shot

Now, I have updated it

2019-07-28 11:23 UTC, niyoceles submitted a review, later dismissed

2019-07-28 18:36 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-07-28 19:04 UTC, kodek-sleuth submitted a review, later dismissed

2019-07-30 11:09 UTC, niyoceles submitted a review, later dismissed
ready to be merged

2019-07-30 11:26 UTC, Hervera approved these changes
Ready to be merged

2019-07-30 11:29 UTC, niyoceles approved these changes

2019-07-30 11:41 UTC, elemanhillary-zz approved these changes
ready for merge

2019-07-30 11:41 UTC, elemanhillary commented on controllers/bookmark.js
> +          error: 'Article is not found.'
`article not found`

2019-07-30 11:52 UTC, merged